-- Roles y permisos de QuindioFlix
-- Ejecutar como el propietario de las tablas

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ADMIN';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_SOPORTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_CONTENIDO';
EXCEPTION WHEN OTHERS THEN NULL;
END;


-- ROL_ADMIN: Administrador de la plataforma
CREATE ROLE ROL_ADMIN;

BEGIN
    FOR t IN (
        SELECT 'PLAN_SUSCRIPCION' AS nm FROM DUAL UNION ALL
        SELECT 'CIUDAD' FROM DUAL UNION ALL
        SELECT 'USUARIO' FROM DUAL UNION ALL
        SELECT 'REFERIDO' FROM DUAL UNION ALL
        SELECT 'PERFIL' FROM DUAL UNION ALL
        SELECT 'DEPARTAMENTO' FROM DUAL UNION ALL
        SELECT 'EMPLEADO' FROM DUAL UNION ALL
        SELECT 'GENERO' FROM DUAL UNION ALL
        SELECT 'CONTENIDO' FROM DUAL UNION ALL
        SELECT 'CONTENIDO_GENERO' FROM DUAL UNION ALL
        SELECT 'CONTENIDO_RELACIONADO' FROM DUAL UNION ALL
        SELECT 'TEMPORADA' FROM DUAL UNION ALL
        SELECT 'EPISODIO' FROM DUAL UNION ALL
        SELECT 'REPRODUCCION' FROM DUAL UNION ALL
        SELECT 'FAVORITO' FROM DUAL UNION ALL
        SELECT 'CALIFICACION' FROM DUAL UNION ALL
        SELECT 'REPORTE_CONTENIDO' FROM DUAL UNION ALL
        SELECT 'PAGO' FROM DUAL UNION ALL
        SELECT 'RESTRICCION_DOMINIO' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ' || t.nm || ' TO ROL_ADMIN';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;

GRANT EXECUTE ANY PROCEDURE TO ROL_ADMIN;
GRANT CREATE USER TO ROL_ADMIN;
GRANT DROP USER TO ROL_ADMIN;
GRANT ALTER USER TO ROL_ADMIN;
GRANT ROL_ANALISTA TO ROL_ADMIN WITH ADMIN OPTION;
GRANT ROL_SOPORTE  TO ROL_ADMIN WITH ADMIN OPTION;
GRANT ROL_CONTENIDO TO ROL_ADMIN WITH ADMIN OPTION;


-- ROL_ANALISTA: Solo lectura y reportes
CREATE ROLE ROL_ANALISTA;

BEGIN
    FOR t IN (
        SELECT 'PLAN_SUSCRIPCION' AS nm FROM DUAL UNION ALL
        SELECT 'CIUDAD' FROM DUAL UNION ALL
        SELECT 'USUARIO' FROM DUAL UNION ALL
        SELECT 'REFERIDO' FROM DUAL UNION ALL
        SELECT 'PERFIL' FROM DUAL UNION ALL
        SELECT 'DEPARTAMENTO' FROM DUAL UNION ALL
        SELECT 'EMPLEADO' FROM DUAL UNION ALL
        SELECT 'GENERO' FROM DUAL UNION ALL
        SELECT 'CONTENIDO' FROM DUAL UNION ALL
        SELECT 'CONTENIDO_GENERO' FROM DUAL UNION ALL
        SELECT 'CONTENIDO_RELACIONADO' FROM DUAL UNION ALL
        SELECT 'TEMPORADA' FROM DUAL UNION ALL
        SELECT 'EPISODIO' FROM DUAL UNION ALL
        SELECT 'REPRODUCCION' FROM DUAL UNION ALL
        SELECT 'FAVORITO' FROM DUAL UNION ALL
        SELECT 'CALIFICACION' FROM DUAL UNION ALL
        SELECT 'REPORTE_CONTENIDO' FROM DUAL UNION ALL
        SELECT 'PAGO' FROM DUAL UNION ALL
        SELECT 'RESTRICCION_DOMINIO' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || t.nm || ' TO ROL_ANALISTA';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;

BEGIN
    FOR p IN (
        SELECT 'SP_REPORTE_CONSUMO' AS nm FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_INGRESOS' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_CONTENIDO_TOP' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_USUARIOS' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_PAGOS' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_SUSCRIPCIONES' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_REPRODUCCIONES' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_CALIFICACIONES' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_FAVORITOS' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_EMPLEADOS' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_CONTENIDO_NUEVO' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_RENTABILIDAD' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_GEOGRAFICO' FROM DUAL UNION ALL
        SELECT 'SP_REPORTE_DISPOSITIVOS' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || p.nm || ' TO ROL_ANALISTA';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;

BEGIN
    FOR v IN (
        SELECT 'MV_CONSUMO_USUARIO' AS nm FROM DUAL UNION ALL
        SELECT 'MV_INGRESOS_MENSUAL' FROM DUAL UNION ALL
        SELECT 'MV_CONTENIDO_POPULAR' FROM DUAL UNION ALL
        SELECT 'MV_USUARIOS_ACTIVOS' FROM DUAL UNION ALL
        SELECT 'MV_PAGOS_ESTADO' FROM DUAL UNION ALL
        SELECT 'MV_REPRODUCCIONES_HORA' FROM DUAL UNION ALL
        SELECT 'MV_CALIFICACIONES_PROMEDIO' FROM DUAL UNION ALL
        SELECT 'MV_FAVORITOS_PERFIL' FROM DUAL UNION ALL
        SELECT 'MV_EMPLEADOS_DEPTO' FROM DUAL UNION ALL
        SELECT 'MV_CONTENIDO_AGREGADO' FROM DUAL UNION ALL
        SELECT 'MV_RENTABILIDAD_PLAN' FROM DUAL UNION ALL
        SELECT 'MV_GEOGRAFICO_USUARIOS' FROM DUAL UNION ALL
        SELECT 'MV_DISPOSITIVOS_USO' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT SELECT ON ' || v.nm || ' TO ROL_ANALISTA';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;


-- ROL_SOPORTE: Soporte al cliente
CREATE ROLE ROL_SOPORTE;

BEGIN
    FOR t IN (
        SELECT 'USUARIO' AS nm, 'SELECT' AS priv FROM DUAL UNION ALL
        SELECT 'PERFIL', 'SELECT' FROM DUAL UNION ALL
        SELECT 'PAGO', 'SELECT' FROM DUAL UNION ALL
        SELECT 'PAGO', 'INSERT, UPDATE' FROM DUAL UNION ALL
        SELECT 'PLAN_SUSCRIPCION', 'SELECT' FROM DUAL UNION ALL
        SELECT 'REFERIDO', 'SELECT' FROM DUAL UNION ALL
        SELECT 'CIUDAD', 'SELECT' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT ' || t.priv || ' ON ' || t.nm || ' TO ROL_SOPORTE';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_SOPORTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;


-- ROL_CONTENIDO: Gestor de catálogo
CREATE ROLE ROL_CONTENIDO;

BEGIN
    FOR t IN (
        SELECT 'CONTENIDO' AS nm, 'SELECT, INSERT, UPDATE, DELETE' AS priv FROM DUAL UNION ALL
        SELECT 'TEMPORADA', 'SELECT, INSERT, UPDATE, DELETE' FROM DUAL UNION ALL
        SELECT 'EPISODIO', 'SELECT, INSERT, UPDATE, DELETE' FROM DUAL UNION ALL
        SELECT 'GENERO', 'SELECT, INSERT, UPDATE, DELETE' FROM DUAL UNION ALL
        SELECT 'CONTENIDO_GENERO', 'SELECT, INSERT, UPDATE, DELETE' FROM DUAL UNION ALL
        SELECT 'CONTENIDO_RELACIONADO', 'SELECT, INSERT, UPDATE, DELETE' FROM DUAL UNION ALL
        SELECT 'REPRODUCCION', 'SELECT' FROM DUAL UNION ALL
        SELECT 'CALIFICACION', 'SELECT' FROM DUAL UNION ALL
        SELECT 'FAVORITO', 'SELECT' FROM DUAL UNION ALL
        SELECT 'EMPLEADO', 'SELECT' FROM DUAL UNION ALL
        SELECT 'DEPARTAMENTO', 'SELECT' FROM DUAL
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'GRANT ' || t.priv || ' ON ' || t.nm || ' TO ROL_CONTENIDO';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;


-- Usuarios de ejemplo
BEGIN
    EXECUTE IMMEDIATE 'DROP USER admin_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
BEGIN
    EXECUTE IMMEDIATE 'DROP USER analista_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
BEGIN
    EXECUTE IMMEDIATE 'DROP USER soporte_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
BEGIN
    EXECUTE IMMEDIATE 'DROP USER contenido_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE USER admin_quindio IDENTIFIED BY admin123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO admin_quindio;
GRANT ROL_ADMIN TO admin_quindio;

CREATE USER analista_quindio IDENTIFIED BY analista123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO analista_quindio;
GRANT ROL_ANALISTA TO analista_quindio;

CREATE USER soporte_quindio IDENTIFIED BY soporte123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO soporte_quindio;
GRANT ROL_SOPORTE TO soporte_quindio;

CREATE USER contenido_quindio IDENTIFIED BY contenido123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO contenido_quindio;
GRANT ROL_CONTENIDO TO contenido_quindio;

COMMIT;
