-- ============================================================
--  QUINDIOFLIX - ROLES Y PERMISOS
--  Versión: 1.0
-- ============================================================
--  Este script crea los roles de la plataforma QuindioFlix
--  con sus privilegios correspondientes.
-- ============================================================

-- ============================================================
-- 0. Limpieza de roles (si existen)
-- ============================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ADMIN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_SOPORTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_CONTENIDO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- ============================================================
-- 1. ROL_ADMIN
--    Administrador de la plataforma
-- ============================================================
CREATE ROLE ROL_ADMIN;

-- CRUD completo en todas las tablas del esquema C_QUINDIOFLIX
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.PLAN_SUSCRIPCION    TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CIUDAD             TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.USUARIO             TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.REFERIDO             TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.PERFIL               TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.DEPARTAMENTO        TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.EMPLEADO            TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.GENERO              TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CONTENIDO           TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CONTENIDO_GENERO    TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CONTENIDO_RELACIONADO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.TEMPORADA          TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.EPISODIO            TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.REPRODUCCION        TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.FAVORITO            TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CALIFICACION        TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.REPORTE_CONTENIDO   TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.PAGO                TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.RESTRICCION_DOMINIO TO ROL_ADMIN;

-- Ejecutar todos los procedimientos, funciones y triggers
GRANT EXECUTE ANY PROCEDURE TO ROL_ADMIN;

-- Crear/eliminar usuarios (administración de cuentas de la plataforma)
GRANT CREATE USER TO ROL_ADMIN;
GRANT DROP USER TO ROL_ADMIN;
GRANT ALTER USER TO ROL_ADMIN;

-- Gestión de roles (para asignar roles de la plataforma)
GRANT ROL_ANALISTA TO ROL_ADMIN WITH ADMIN OPTION;
GRANT ROL_SOPORTE  TO ROL_ADMIN WITH ADMIN OPTION;
GRANT ROL_CONTENIDO TO ROL_ADMIN WITH ADMIN OPTION;


-- ============================================================
-- 2. ROL_ANALISTA
--    Analista de datos / gerencia
-- ============================================================
CREATE ROLE ROL_ANALISTA;

-- SELECT en todas las tablas (solo lectura)
GRANT SELECT ON C_QUINDIOFLIX.PLAN_SUSCRIPCION    TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.CIUDAD             TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.USUARIO             TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.REFERIDO             TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.PERFIL               TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.DEPARTAMENTO        TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.EMPLEADO            TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.GENERO              TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.CONTENIDO           TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.CONTENIDO_GENERO    TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.CONTENIDO_RELACIONADO TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.TEMPORADA          TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.EPISODIO            TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.REPRODUCCION        TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.FAVORITO            TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.CALIFICACION        TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.REPORTE_CONTENIDO   TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.PAGO                TO ROL_ANALISTA;
GRANT SELECT ON C_QUINDIOFLIX.RESTRICCION_DOMINIO TO ROL_ANALISTA;

-- Ejecutar procedimientos de reportes (patrón SP_REPORTE_*)
-- Se envuelven en bloques PL/SQL porque los procedimientos pueden no existir aún.
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_CONSUMO         TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_INGRESOS        TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_CONTENIDO_TOP   TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_USUARIOS        TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_PAGOS           TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_SUSCRIPCIONES   TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_REPRODUCCIONES  TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_CALIFICACIONES  TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_FAVORITOS       TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_EMPLEADOS       TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_CONTENIDO_NUEVO TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_RENTABILIDAD    TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_GEOGRAFICO      TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_REPORTE_DISPOSITIVOS    TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Acceso a vistas materializadas (se ignora si aún no existen)
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_CONSUMO_USUARIO        TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_INGRESOS_MENSUAL       TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_CONTENIDO_POPULAR      TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_USUARIOS_ACTIVOS       TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_PAGOS_ESTADO           TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_REPRODUCCIONES_HORA    TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_CALIFICACIONES_PROMEDIO TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_FAVORITOS_PERFIL       TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_EMPLEADOS_DEPTO        TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_CONTENIDO_AGREGADO     TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_RENTABILIDAD_PLAN      TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_GEOGRAFICO_USUARIOS    TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON C_QUINDIOFLIX.MV_DISPOSITIVOS_USO       TO ROL_ANALISTA';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ============================================================
-- 3. ROL_SOPORTE
--    Soporte al cliente
-- ============================================================
CREATE ROLE ROL_SOPORTE;

-- SELECT en tablas de usuarios, perfiles, pagos y suscripciones
GRANT SELECT ON C_QUINDIOFLIX.USUARIO             TO ROL_SOPORTE;
GRANT SELECT ON C_QUINDIOFLIX.PERFIL               TO ROL_SOPORTE;
GRANT SELECT ON C_QUINDIOFLIX.PAGO                TO ROL_SOPORTE;
GRANT SELECT ON C_QUINDIOFLIX.PLAN_SUSCRIPCION    TO ROL_SOPORTE;
GRANT SELECT ON C_QUINDIOFLIX.REFERIDO             TO ROL_SOPORTE;
GRANT SELECT ON C_QUINDIOFLIX.CIUDAD             TO ROL_SOPORTE;

-- INSERT/UPDATE en PAGOS (para registrar pagos manuales, ajustes, reembolsos)
GRANT INSERT, UPDATE ON C_QUINDIOFLIX.PAGO          TO ROL_SOPORTE;

-- Ejecutar procedimiento para cambiar plan de suscripción
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C_QUINDIOFLIX.SP_CAMBIAR_PLAN TO ROL_SOPORTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- ============================================================
-- 4. ROL_CONTENIDO
--    Gestor de catálogo
-- ============================================================
CREATE ROLE ROL_CONTENIDO;

-- CRUD completo en tablas de contenido
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CONTENIDO           TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.TEMPORADA          TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.EPISODIO            TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.GENERO              TO ROL_CONTENIDO;

-- CRUD en tablas de relación de contenido
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CONTENIDO_GENERO    TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_QUINDIOFLIX.CONTENIDO_RELACIONADO TO ROL_CONTENIDO;

-- SELECT en reproducciones (para ver estadísticas de consumo)
GRANT SELECT ON C_QUINDIOFLIX.REPRODUCCION        TO ROL_CONTENIDO;

-- SELECT en calificaciones (para ver feedback de usuarios)
GRANT SELECT ON C_QUINDIOFLIX.CALIFICACION        TO ROL_CONTENIDO;

-- SELECT en favoritos (para ver popularidad)
GRANT SELECT ON C_QUINDIOFLIX.FAVORITO            TO ROL_CONTENIDO;

-- SELECT en tablas de referencia necesarias
GRANT SELECT ON C_QUINDIOFLIX.EMPLEADO            TO ROL_CONTENIDO;
GRANT SELECT ON C_QUINDIOFLIX.DEPARTAMENTO        TO ROL_CONTENIDO;


-- ============================================================
-- 5. Asignación de roles a usuarios de ejemplo
-- ============================================================

-- Limpieza de usuarios de ejemplo (si existen)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER admin_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER analista_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER soporte_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER contenido_quindio';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Usuario administrador
CREATE USER admin_quindio IDENTIFIED BY admin123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO admin_quindio;
GRANT ROL_ADMIN TO admin_quindio;

-- Usuario analista
CREATE USER analista_quindio IDENTIFIED BY analista123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO analista_quindio;
GRANT ROL_ANALISTA TO analista_quindio;

-- Usuario soporte
CREATE USER soporte_quindio IDENTIFIED BY soporte123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO soporte_quindio;
GRANT ROL_SOPORTE TO soporte_quindio;

-- Usuario contenido
CREATE USER contenido_quindio IDENTIFIED BY contenido123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO contenido_quindio;
GRANT ROL_CONTENIDO TO contenido_quindio;


COMMIT;

-- ============================================================
-- FIN DEL SCRIPT DE ROLES
-- ============================================================
